### ISSUE TITLE
incomplete loop .. repeat while reading EastAsianWidth.txt

### ISSUE THREAD

**Issue by dohyunkim** [latex3/unicode-data#1]
After the first loop of reading EastAsianWidth.txt, it never reaches the next line.
In othe words, after reading the line:

```
0000..001F;N     # Cc    [32] <control-0000>..<control-001F>
```

the loop is terminated unexpectedly. Possibly it is related to the nested loop .. repeat in `parseunicodedataIII`.

Again, it seems that line 188 of load-unicode-xetex-classes.tex should be corrected as follows:

```
\global\XeTeXcharclass\count0=\XeTeXcharclassID
```

as stated in the comment: class mappings _may be over-ridden by defining `\XeTeXcharclass<class>`._

**Comment by dohyunkim** [comment]
Thanks for quick fix, which however introduced a new bug.
When loading load-unicode-xetex-classes, I get error message:

```
! TeX capacity exceeded, sorry [save size=80000].
```

**Comment by josephwright** [comment]
Mumble: I'll sort :-)

**Comment by josephwright** [comment]
Ah, I see where the issue is. It's not the loop nesting (saving/restoring `\body` is fine), it's the number of `\EAW@...` names that are needed. I'll need to re-think the approach: either they have to be global and get tidied up or I need an alternative data structure.

**Comment by josephwright** [comment]
Will probably have to wait until this evening to fix it.

**Comment by josephwright** [comment]
Note that simply using `\gdef` fails as the name is generated by `\csname` and so we still have save-stack build up. An alternative approach is going to be needed.

**Comment by josephwright** [comment]
I'll upload to CTAN shortly but a once-over the new approach would be welcome!

**Comment by dohyunkim** [comment]
Currently, the last character of a range does not get assigned a new character class. For instance,

```
\showthe\XeTeXcharclass "4E00  % prints 1
\showthe\XeTeXcharclass "9FD5  % prints 0
```

**Comment by dohyunkim** [comment]
The same issue of incomplete reading, related to nested loop .. repeat, also exists in load-unicode-data.tex. 

```
\showthe\catcode"3400  % prints 11.
\showthe\catcode"4E00  % prints 12.
```

**Comment by josephwright** [comment]
OK, I'm adding some tests for this type of thing so I'll sort as part of that.
