### ISSUE TITLE
CJ letters should belong to XeTeXcharclass 1

### ISSUE THREAD

**Issue by zr-tex8r** [latex3/unicode-data#2]
After loading load-unicode-xetex-classes.tex, we have:
- `\XeTeXcharclass"3041=0` (U+3041 HIRAGANA LETTER SMALL A is a non-CJK)
- `\XeTeXcharclass"3042=1` (U+3042 HIRAGANA LETTER A is a normal CJK)

But this is very strange, because U+3041 (small-a) is a full-fledged kana letter just like U+3042 (a), and at least must be treated as a CJK letter.

U+3041 belongs to the line break class ‘CJ’, and what [UAX #14](http://unicode.org/reports/tr14/) states on this class is summarized as follows:
- If you want more line-break points (normal kinsoku), then treat CJ as ID.
- If you want less line-break points (strict kinsoku), then treat CJ as NS.

That is, CJ characters must have `\XeTeXcharclass` value 1 (normal) or 3 (strict). Of these two options, I recommend using the value 1, because the character class 3 is often seen as a group for punctuations and kana letters belonging to this group sometimes causes trouble in some package (which relies on the “old settings.”)

**Comment by josephwright** [comment]
I see that `unicode-letters.tex` does the same as `load-unicode-xetex-classes.tex`, so this is 'inherited'. I'll give this a bit of thought.
