### ISSUE TITLE
OpenType Mirroring data file

### ISSUE THREAD

**Issue by zauguin** [latex3/unicode-data#8]
For https://github.com/latex3/luaotfload/issues/61 we need OpenType's "OpenType Mirroring Pairs List" and I am not sure if it should be shipped in luaotfload or in unicode-data:

It is a copy of Unicode's `BidiMirroring.txt` from Unicode 5.1.0 (it will never be updated). So it's not really a Unicode data file (at least not from current Unicode versions), but it still "feels" like one and doesn't really fit into luaotfload.

What do you think?

**Comment by josephwright** [comment]
It's still in the UCD: https://www.unicode.org/Public/12.1.0/ucd/BidiMirroring.txt. Is there a reason it has to be the 5.1.0 one?

**Comment by josephwright** [comment]
Reading the comments in the file: if we ship, it should be as two files, one the 'live' one and one the frozen one (likely called `BidiMirroring-510.txt`)

**Comment by zauguin** [comment]
@josephwright Beside that OpenType (and the comments) explicitly request the 5.1.0 version, there are practical reasons for this:

In OpenType, mirroring happens in two steps. First all replacements from this list are applied, then additional OpenType features are used to allow customized mirror glyphs and mirroring pairs not (yet) documented in Unicode. This ensures that fonts can mirror new Unicode glyphs without requiring updates for all programs by replicating Unicode mirroring pairs of newer versions in OpenType lookups. Now if we would use the current file, such fonts would break because we would mirror before applying the features and the font feature would mirror every glyph back to it's original.

Currently in luaotfload I used the name `OpentypeMirroring.txt` to make the context clear, but `BidiMirroring-510.txt` would be fine too.

**Comment by josephwright** [comment]
@zauguin OK, sounds like the right call is to include the older file somewhere under an appropriate name: I think that does fall into the scope of `unicode-data`.

**Comment by FrankMittelbach** [comment]
> I think that does fall into the scope of `unicode-data`.

I agree, and I would call it `BidiMirroring-510.txt` to make the relationship to the live one clear. Plus perhaps somewhere a remark why it is there and that it is used in OpenType processing as a fixed point.

**Comment by josephwright** [comment]
I wonder if `BidiMirroring-5-1.txt` is better? The only other non-UCD file we have is `MathClass-15.txt`, but there we don't show the minor version. I'm mindful that we could end up in trouble with some future files if major/minor version overlap.

**Comment by FrankMittelbach** [comment]
Maybe, or even -5-1-0. It is probably better not to use dots even though that would be more accurate.

**Comment by josephwright** [comment]
Yes, I'd ruled out dots as they can cause confusion. As you say, if we are including version number, probably best to give the lot. @zauguin would that plus the 'vanilla' file, with a short piece of text in the README to explain the logic, be OK?

**Comment by zauguin** [comment]
Also for conceptual reasons I would include the minor version: We need this specific version, even if 5.1.1 would exists we wouldn't want it. For MathClass we probably would want to update the file if a new minor version would exists.
So yes, looks good to me. If you want to change the comments, we could consider basing it on the OpenType version instead of the Unicode one (https://docs.microsoft.com/en-us/typography/opentype/spec/ompl)

**Comment by josephwright** [comment]
I think going with official Unicode Consortium files is best: that way we are making no value judgement at all on them.

**Comment by zauguin** [comment]
I added the files in a605fbe3b724b1e32be5470e216cadb5c0de09ce.
@josephwright Is that sufficient information in the README or should we add further information?
